### ISSUE TITLE
GET requests with "Content-Length" header

### ISSUE THREAD

**Issue by sjoller** [Lenius/economic-php-client#4]
It seems the "Content-Length" header is added automatically, including on GET requests - I'm not completely sure where, but it's not in your code. I've seen some mentions of Apache adding it, but have not looked into their source code.

Anyway the Economic REST API does not support GET requests with a body (as indicated by the "Content-Length" header) - actually it's their load balancer blocking the requests, after they switched to Google Cloud. The reasoning (apparently) is, that it's not condoned in the RFC.

The only solution I've had working is, to manually set the "Content-Length" header to 0, for GET requests. Obviously this will not work for any type of requests with a body.

So the problem is, the "Content-Length" header must be set to 0 for GET requests (possible true for other types with no body, too), but as headers are set when initiating the client, it's not possible to change those later.

**Comment by stockholmz** [comment]
@sjoller The problem is within this library unfortunately. 
I've just spent 2 days of debugging because of e-conomics change of loadbalancer.

The library does not implement curl_close itself, and headers are not reset properly. (My guess is because its a reuseable instance)
I fixed this by editting **(pull request coming up)** Request.php:get() inserting this
`curl_setopt($this->client->ch, CURLOPT_HTTPGET, TRUE);`

The better solution would most likely be to implement curl_close properly.
However I need to move on, and this made it work.

**Comment by cjonstrup** [comment]
Thanks - I will test more to day

**Comment by cjonstrup** [comment]
@stockholmz thanks for the solution.

**Comment by stockholmz** [comment]
@cjonstrup You are welcome. Thanks for a great package.
